apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-ui
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
      - name: todo-ui
        image: acrtodoappdev01.azurecr.io/microtodoui:12
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acr-creds
